theme: jekyll-minima
title: Next Generation Researcher
description: A support program for early career researchers on the IUPUI campus designed to foster innovative, open, and sustainable research practices.

language: en_US
show_downloads: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - resourcefair
 - fellowship

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
